language: node_js

node_js:
- '5.2'
- '5.1'
- '0.12'
- '0.11'
- '0.10'

env:
  global:
    - secure: "RaGcSG91bRzPlmfSqCDiM/byECBEUUMvlyZyhkFrJ6ASLMa05ITor1j1WG6FE5NhL0WjgygLmgwpu+omh9QQ/yUA3SYWJFI0AvqYVXqIEbuGyi/KPmdXJS7ghqOeJJppGGbUQXx2lHjvgI5zObd423OtdLggMPPR/7MagemKPMu5HMV9fnINAQ47FEj6uIdSv7R39vvQKhaRuGQmTXdi5Hh4aU8v4ejRejPf571QMJV6mIeYafJQysfhtPVZSIhV8yRzSJd7j4aSbnK7chykoNc4muAao3NaaNRyLJ3TnAC4CBPlntd+iR4mJkbk7lraJAYyVOfi0xtimL0gQJvdHgWrzXM0ZCr3KjOBhfMN5DC+Qs+YqwNXcDrfFqfIoaFSEmK3VW5/xdFz/6424/Aa2O5ZrXzcHMvvBIBb+fVH3XMrbp2Ze6V/KPl6MAK+tDjwY5BhMcgV7sw40rWhEz5T5cYhLw7midCnj+bY1ZcPEC+TnCafWerIZiVaEP3DDIwzuL9XrzGT82wgHQ1XVNgorTxJ5SvIv4RblDx7ICjiifnq824QT1zlfvQJW50EA7l43nahRnpbQCMgIO735MjuGJd2ygdt5mBZwckqJFacg9zwFJR8wjsHva7Wp3CiPRUfphCSBerXmr6s2lHe23c7LrWyIJSKt7VqrdkbIsIoYcE="
    - secure: "MNrpVhBp80t2Mm7e1c75RgR7ix9b9kBgVSxnHl0yNpk94KFhUaWCXCKtUYPdIxgolEKd9WA6dykqyY+zSzAXnUshQ8FtnP69npzEQEqP2Cb+13WDSlxFg8GBYACWkAhO2djGYRZmI0uJZF7A95zf+KPSifgPk/dY56dA13FpkkAJpRx8dMdbjVYP3NBo+Z2EViYBIXnkEcOr2wyzezMZYKaokfAW/iQgFauzB7xtYKIeKjUasE9ShhRVm8DU+wkZI3+N5f0mYO0aDEb0n8ZBw81NO/zmGWRA4xjzZNJEwyylYBBXb/RAsfvqsztcOTBg8EGheJN0BJSxUaqXjte+phNQPXMAFrMdsZwugHjdG0vw9iaDlY251dX/h495U07LZpztg50LSnUSq3NG2cpZLNWrfK8IUWvS3Ia6PwprSAKclnRIYZ4i89USG31RpIJ07UgsQveFw+yoXtJpAPHXp6bsJAr8sgd0S3vy74oaALIH2QqrGi9jU19363Q3bzP2heUoF20YHNbuAGHEg5F2/NRsFOYGZSWYwV60adSAvMgM6Kw4h1hqam1ChQEsDhuUpDJeY1fYB+okhDGeeQCaJZGU1wmXPvAR9q/a08sf+LPp1q9njS405URLhUaw2VWhXXBzbk7F3yLZs/Fwx5TksVcraM2x+ZN0Ku08pbzl8ec="
    - secure: "ng5Ap98a41+uHZOtNgJVc3mdynQQG7lIITFqBfuQX8vnaHGOhiSSbjWWw8v/Yn13n7wI7COJz3BnZmG21wEFdFPp3Ib2KM7ZY8FICq2+l2G8R1WWEmRlT76nKsnQLzo3GgCxPrnl0ORxKpJdbGsRlE1ixU9KsFkYupkSaKt3LJyhkDPH7ag7VxsFUVK2AdD2d0zAPqCGZYhm6L7CxYwGOm8boiJOwpO8sIIKy068niJjFCw7q9I1Rl8JvAKYLnsmwH6V7NDSiX/MO1gJfQ5rQqv+c+hbonn+MR/UAnPS1lfIIX3jKxh6MjPjp8oH/K8NMLBGpl78B1mf29JwDbGcwN11eN+OHtyBQgqfhZHHGvbVJHrnam0rqxS/sWJCXYnGeypDz693n8rNwOSxZxDJm30rq5F1Zo6a2j80fwfPqnIeQM/PoD3qBH4iUlubEL+8u+rKLRBInSjGY+eSNBft6CuclWJ4zD63ApuJK/J+tDvYOUpW7fqcevlFDuPS2OvIxSpXExD0/UXdQcaGUxssbG7kkrrlOkNNegVUqs3yEfoTC9t9O1pofBCI6PCmXnVAj8wwo+QlHu5CpzA2F6U8yj3BwIaWXZS5A6csahdrhrip6AXVamdmxow8c1kDhuun3sAMPP9r2RmUWkg8dHGX8nlcNKxTsvtWZ9Sfbb/18uE="
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=yamadapc/github-trending-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
