sudo: required

services:
  - docker

language: node_js

node_js:
- '5.2'
- '4.1'
- '0.12'
- '0.10'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  echo "$TRAVIS_NODE_VERSION";
  if [ "$TRAVIS_BRANCH" == "master" ] &&
     [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
     [ "$TRAVIS_NODE_VERSION" == "5.2" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS";
    export REPO=yamadapc/github-trending-api;
    export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`;
    docker build -f Dockerfile -t $REPO:$COMMIT .;
    docker tag $REPO:$COMMIT $REPO:$TAG;
    docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER;
    docker push $REPO;
  else
    echo "Skipping image build";
  fi;
